server:
  port: 4041
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: engin
    password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-server
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/DBMySelfAuthService
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secretKey: ${Myselfsecretkey}
  issuer: ${Myselfissuer}

rabbitmq:
  auth-exchange: auth-exchange
  register-binding-key: register-key
  register-queue: register-queue
  activation-binding-key: activation-key
  activation-queue: activation-queue
  mail-binding-key: mail-key
  mail-queue: mail-queue

redis:
  host: localhost
  port: 6379
