server:
  port: 5050

spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/auth-service-DB
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
